export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PORTFOLIO_REPOSITORY = 'PORTFOLIO_REPOSITORY';
export const IMAGE_REPOSITORY = 'IMAGE_REPOSITORY';
export const COMMENT_REPOSITORY = 'COMMENT_REPOSITORY';
